# Generated by Django 3.1.7 on 2021-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210309_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='parent_code',
            field=models.IntegerField(blank=True, default=1, verbose_name='Country Parent Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_code',
            field=models.IntegerField(blank=True, default=1, verbose_name='Location Parent Code'),
            preserve_default=False,
        ),
    ]
