# Generated by Django 3.1.7 on 2021-03-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210309_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='type',
            field=models.CharField(max_length=256, verbose_name='Country Type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(max_length=256, verbose_name='Location Type'),
        ),
    ]
