# Generated by Django 3.1.7 on 2021-03-09 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_auto_20210309_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.CharField(max_length=256, verbose_name='Id in Api')),
                ('engine', models.CharField(max_length=256, verbose_name='Search Engine')),
                ('keyword', models.CharField(max_length=256, verbose_name='Search keyword')),
                ('start', models.DateTimeField(verbose_name='Date Add')),
                ('end', models.DateTimeField(verbose_name='Date Done')),
                ('lang', models.CharField(default='en', max_length=2, verbose_name='Language Code')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
