# Generated by Django 3.1.7 on 2021-03-09 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Done'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_api',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Id in Api'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 21, 50, 33, 11377), verbose_name='Date Add'),
        ),
    ]
