# Generated by Django 3.1.7 on 2021-03-10 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210309_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Search Engine Name')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 11, 19, 9, 742262), verbose_name='Date Add'),
        ),
        migrations.AlterField(
            model_name='order',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.searchengine', verbose_name='Search Engine'),
        ),
    ]
