# Generated by Django 3.1.7 on 2021-03-10 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210310_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.searchengine', verbose_name='Search Engine'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 11, 20, 30, 91462), verbose_name='Date Add'),
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Search Engine Name'),
        ),
    ]
