# Generated by Django 3.1.7 on 2021-03-10 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210310_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchengine',
            name='display_name',
            field=models.CharField(default=1, max_length=256, verbose_name='Search Engine Display Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 11, 21, 47, 598053), verbose_name='Date Add'),
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Search Engine Api Name'),
        ),
    ]
