# Generated by Django 3.1.7 on 2021-03-10 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210310_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 11, 33, 7, 327984, tzinfo=utc), verbose_name='Date Add'),
        ),
    ]
