# Generated by Django 3.1.7 on 2021-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210310_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Add'),
        ),
    ]
