# Generated by Django 3.1.7 on 2021-03-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210310_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, verbose_name='Type of element')),
                ('rank_group', models.IntegerField(verbose_name='group rank in SERP')),
                ('rank_absolute', models.IntegerField(verbose_name='absolute rank in SERP')),
                ('domain', models.CharField(max_length=256, verbose_name='domain in SERP')),
                ('title', models.CharField(max_length=256, verbose_name='title of the results element in SERP')),
                ('description', models.TextField(verbose_name='description of the results element in SERP')),
                ('url', models.CharField(max_length=256, verbose_name='relevant URL in SERP')),
                ('breadcrumb', models.CharField(max_length=256, verbose_name='breadcrumb in SERP')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order of element')),
            ],
        ),
    ]
