# Generated by Django 3.1.7 on 2021-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_dataorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataorder',
            name='breadcrumb',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='breadcrumb in SERP'),
        ),
        migrations.AlterField(
            model_name='dataorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description of the results element in SERP'),
        ),
        migrations.AlterField(
            model_name='dataorder',
            name='domain',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='domain in SERP'),
        ),
        migrations.AlterField(
            model_name='dataorder',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='title of the results element in SERP'),
        ),
        migrations.AlterField(
            model_name='dataorder',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Type of element'),
        ),
        migrations.AlterField(
            model_name='dataorder',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='relevant URL in SERP'),
        ),
    ]
